export const TEXT_CONTENT = {
    beginner: [
        "Bananas are curved because they grow towards the sun!",
        "Honey never spoils; you can eat 3000-year-old honey.",
        "Octopuses have 3 hearts & blue blood inside them.",
        "Did you know? A day on Venus is longer than its year.",
        "The Eiffel Tower grows up to 15cm in summer heat.",
        "Australia is wider than the moon by almost 600km.",
        "Human teeth cannot heal themselves naturally.",
        "The heart of a shrimp is located in its head?!",
        "Your heart stops for a millisecond when you sneeze.",
        "Pigs cannot look straight up into the sky.",
        "A group of bright pink flamingos is called a flamboyance.",
        "Cows have best friends and get stressed when separated.",
        "Butterflies can actually taste their food using their feet!",
        "Sea otters can hold their breath much longer than dolphins.",
        "A 'jiffy' is an actual unit of time: 1/100th of a second.",
        "Koalas have cube-shaped poop to stop it rolling away.",
        "Peanuts are technically not nuts; they are legumes.",
        "Sloths are so slow that green algae can grow on their fur.",
        "You cannot hum while holding your nose closed. Try it!",
        "Snails can sleep for up to three years at a single time.",
        "Elephants are the only mammals in the world that cannot jump.",
        "An ostrich's eye is physically bigger than its whole brain.",
        "Frogs can freeze solid without dying and thaw out later.",
        "Giraffes hum to each other at night to communicate safely.",
        "A blue whale's tongue weighs as much as an adult elephant.",
        "The unicorn is actually the national animal of Scotland!",
        "Cats share 95.6% of their genetic makeup with wild tigers.",
        "Bamboo grows incredibly fast, up to 35 inches in a single day.",
        "The loudest animal in the world is the giant sperm whale.",
        "Hummingbirds flap their tiny wings up to 80 times a second.",
        "Snow leopards have the thickest fur of any large cat species.",
        "Starfish have a tiny eye at the end of each of their arms.",
        "Owls do not have eyeballs; they have long eye tubes instead.",
        "A chameleon's tongue is twice the length of its entire body.",
        "Dolphins have specific names for each other in their language.",
        "Sea turtles hold hands while sleeping so they stay together.",
        "Apples float in water because they are made of 25% air.",
        "Penguins can drink salt water because of a special body gland.",
        "A single fluffy cloud can weigh more than a million pounds!",
        "Dogs have 32 muscles in each ear to help them hear perfectly."
    ],
    intermediate: [
        "The core temperature of the Earth is estimated to be around 5,200°C.",
        "A typical lightning strike heats the surrounding air to roughly 30,000 Kelvin!",
        "The Hubble Space Telescope travels at a speed of 17,000 mph (27,300 km/h).",
        "Water's chemical formula is H2O, meaning two hydrogen atoms and one oxygen atom.",
        "The human genome contains approximately 3.2 billion base pairs of DNA.",
        "Sound waves travel through dense steel at about 5,960 meters per second.",
        "Saturn's Great Red Spot is a massive storm spanning over 10,000 miles!",
        "To escape Earth's gravity, a rocket needs to reach 11.2 km/s (Escape Velocity).",
        "An adult brain weighs about 3 pounds (1.4 kg) and uses 20% of the body's energy.",
        "The processing speed of a modern computer chip is measured in Gigahertz (GHz).",
        "Mount Everest's peak sits exactly 8,848.86 meters above global sea level.",
        "Carbon-14 is a radioactive isotope used for dating ancient organic materials.",
        "The deepest point in the ocean, Challenger Deep, descends to 10,928 meters.",
        "Light from the Sun takes approximately 8 minutes and 20 seconds to reach us.",
        "The freezing point of absolute zero is mathematically defined as -273.15°C.",
        "In digital binary code, the number 5 is strictly represented by the sequence 0101.",
        "The human eye can visibly distinguish between 10 million different color shades.",
        "Earth's atmosphere is composed of 78% nitrogen, 21% oxygen, and 1% trace gases.",
        "The atomic number of Gold (Au) is 79, making it a heavy, precious metal.",
        "Voyager 1 became the first human-made object to enter interstellar space in 2012.",
        "A standard silicon wafer can contain over 50,000,000 microscopic transistors!",
        "The massive planet Jupiter completes one full rotation on its axis in just 9.9 hours.",
        "Kinetic energy is calculated using the standard physics formula: KE = 0.5 * m * v^2.",
        "Human blood types are categorized into four main medical groups: A, B, AB, and O.",
        "The Mariana Trench water pressure is a crushing 1,086 bars (15,750 psi).",
        "The radioactive half-life of Uranium-238 is an astonishing 4.468 billion years.",
        "One astronomical unit (1 AU) is the average distance from the Earth to the Sun.",
        "Quantum computers process data using qubits, which can represent 0, 1, or both!",
        "The speed of light through a pure diamond slows down to 124,000 miles per second.",
        "The famous Fibonacci sequence naturally begins with 0, 1, 1, 2, 3, 5, 8, 13, and 21."
    ],
    pro: [
        "The five red lights instantly go out! The grid roars into Turn 1 at 300 km/h.",
        "DRS is enabled on lap three. The rear wing opens for a massive +15 km/h boost!",
        "Tire temperatures are exceeding 110°C. The soft compound is degrading much faster than expected.",
        "He locked the front-right brake at the hairpin. That mistake cost him 0.452 seconds in Sector 2!",
        "Box, box, box for hard tires! The pit crew executes a flawless 2.1-second stop.",
        "Aerodynamic downforce pushes the car into the track. It corners at a neck-breaking 5G lateral force.",
        "The safety car is deployed due to debris. Delta times must be strictly maintained on the steering wheel!",
        "The V6 Turbo Hybrid engine recovers kinetic energy. MGU-K deployment is critical for straight-line speed.",
        "Pole position was secured by a margin of just 0.012 seconds. Every millimeter of the apex mattered!",
        "The checkered flag waves as the crowd erupts! It's a spectacular Grand Slam victory this weekend.",
        "Telemetry shows a sudden drop in fuel pressure. The race engineer frantically analyzes the data logs.",
        "Slipstreaming down the main straight reduces drag. He dives down the inside for a breathtaking overtake!",
        "Track temperature dropped by 5°C before qualifying. The medium tires are struggling to find optimal grip.",
        "A 10-second time penalty was issued for causing a collision. He must push hard to build a sufficient gap!",
        "The halo device deflected the massive impact perfectly. Carbon fiber shattered, but the driver walked away.",
        "Sector 1 is painted purple on the timing screens! He is absolutely flying through the high-speed chicanes.",
        "Overtaking at Monaco is notoriously impossible. The barrier is kissed by a mere fraction of an inch!",
        "Battery charge is critically low on the final lap. He must defend the racing line without ERS assistance.",
        "Rain starts spotting on the visor at Turn 4. The pit wall gambles early by switching to intermediate tires.",
        "Downshifting from 8th gear to 2nd takes just milliseconds. The carbon-ceramic brakes glow bright red under load!"
    ],
    syntax: [
        "for (let i = 0; i < array.length; i++) { sum += array[i]; }",
        "const toggleTheme = () => document.body.classList.toggle('dark-mode');",
        "document.querySelectorAll('.active').forEach(el => el.classList.remove('hidden'));",
        "document.getElementById('btn').addEventListener('click', runAction);",
        "if (!Number.isInteger(input) || input < 0) throw new TypeError(\"Invalid input\");",
        "def calculate_average(numbers): return sum(numbers) / len(numbers)",
        "dict_keys = {k: v for k, v in my_dict.items() if v is not None}",
        "[word.upper() for word in text.split() if len(word) > 3]",
        "with open('data.json', 'r') as file: config = json.load(file)",
        "df['total_cost'] = df['price'] * df['quantity'] * (1 - df['discount'])",
        "if __name__ == \"__main__\": app.run(host=\"0.0.0.0\", port=8080, debug=True)",
        "lambda x, y: x * y if x > y else x + y",
        "def fibonacci(n): return n if n <= 1 else fibonacci(n-1) + fibonacci(n-2)",
        "try { await fetchData(); } catch (err) { console.error(err); }",
        "numbers.sort((a, b) => a - b).filter(n => n % 2 === 0);",
        "const { title, author: { name, age } } = bookData;",
        "setTimeout(() => resolve(\"Success!\"), 2500);",
        "Object.entries(userData).forEach(([key, value]) => console.log(key, value));",
        "function* generateSequence() { yield 1; yield 2; return 3; }",
        "if (username === null || password === undefined) return false;",
        "array.filter(item => item.value > 10).map(item => item.id);",
        "System.out.println(\"Hello, World!\"); return 0;",
        "public static void main(String[] args) { init(); }",
        "public class Vehicle { private String make; private int year; }",
        "public static final double PI = 3.141592653589793;",
        "int[] arr = new int[10]; for (int i = 0; i < arr.length; i++) arr[i] = i * 2;",
        "List<String> names = employees.stream().map(Employee::getName).collect(Collectors.toList());",
        "public interface Repository<T, ID> { Optional<T> findById(ID id); void save(T entity); }",
        "String jsonString = new ObjectMapper().writeValueAsString(userObject);",
        "try (Connection conn = DriverManager.getConnection(DB_URL, USER, PASS)) { stmt.execute(); }",
        "import React, { useState, useEffect } from 'react';",
        "const [count, setCount] = useState(0);",
        "import { BrowserRouter as Router, Route } from 'react-router-dom';",
        "app.get('/api/data', (req, res) => { res.json({status: 200}); });",
        "useEffect(() => { const timer = setInterval(tick, 1000); return () => clearInterval(timer); }, []);",
        "app.post('/login', passport.authenticate('local', { successRedirect: '/' }));",
        "const store = configureStore({ reducer: { user: userReducer, cart: cartReducer } });",
        "app.use(cors({ origin: 'https://example.com', credentials: true }));",
        "export const useAuth = () => { const context = useContext(AuthContext); return context; };",
        "return <div className=\"flex items-center justify-center p-4\">{children}</div>;",
        "module.exports = { entry: './src/index.js', output: { filename: 'bundle.js' } };",
        "SELECT * FROM users WHERE active = 1 ORDER BY date DESC;",
        "SELECT department, COUNT(id) FROM employees GROUP BY department HAVING COUNT(id) > 5;",
        "UPDATE inventory SET stock = stock - 1 WHERE item_id = 492 AND stock > 0;",
        "SELECT e.name, m.name AS manager FROM employees e LEFT JOIN employees m ON e.manager_id = m.id;",
        "INSERT INTO logs (action, timestamp) VALUES ('LOGIN', CURRENT_TIMESTAMP);",
        "SELECT AVG(salary) OVER (PARTITION BY department_id) FROM salaries;",
        "std::vector<int> nums = {1, 2, 3}; nums.push_back(4);",
        "template <typename T> T max(T a, T b) { return (a > b) ? a : b; }",
        "std::unique_ptr<MyClass> ptr = std::make_unique<MyClass>();"
    ]
};

export const TOTAL_LEVELS = 10;

export const GAME_CONFIG = {
    beginner: { subLevels: 4 },
    intermediate: { subLevels: 3 },
    pro: { subLevels: 2 },
    syntax: { subLevels: 5 }
};
